### PR TITLE
Automatically update the .gitignore with .task

### PR DESCRIPTION
**Pull request by deviantintegral**
"This should be simple".... ends up stepping through code in multiple projects.

This PR automatically configures `.gitignore` on install to ignore `.task` as suggested by https://taskfile.dev/#/usage?id=by-fingerprinting-locally-generated-files-and-their-sources.

### CODE REVIEW

**Comment by justafish** [comment]
This doesn't seem to update my .gitignore :thinking: Tested with:
- no .gitignore
- empty .gitignore
- .gitignore with an existing line

**Comment by deviantintegral** [comment]
Did you override the branch in your project? I was testing using a path repo with this checked out.

—
Andrew

**Comment by justafish** [comment]
I did

**Comment by deviantintegral** [comment]
Things broke for me when I updated composer. It looks like Composer now uses promises for `install()` and `update()` in LibraryInstaller. I converted that over, as well as added some tests.

**Comment by deviantintegral** [comment]
Given the tests I've added, I think I've solved the above issues. I'm going to merge this so I can test this completely from `composer require` on a project without any manual repositories. Feel free to leave notes and I can open a followup if needed.

**Pull request merged**
